# Generated by Django 2.0 on 2017-12-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname_en', models.CharField(max_length=150)),
                ('orgname_fr', models.CharField(max_length=150)),
                ('desc_en', models.TextField(blank=True, null=True)),
                ('desc_fr', models.TextField(blank=True, null=True)),
                ('request_no', models.CharField(max_length=150)),
            ],
        ),
    ]
