# Generated by Django 2.0 on 2017-12-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxtdemo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ati',
            name='month',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='ati',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
