# Generated by Django 2.0.5 on 2018-05-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname_en', models.CharField(max_length=150)),
                ('orgname_fr', models.CharField(max_length=150)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('month', models.CharField(blank=True, help_text='Enter number 1 to 12', max_length=4)),
                ('desc_en', models.TextField(blank=True, null=True)),
                ('desc_fr', models.TextField(blank=True, null=True)),
                ('request_no', models.CharField(max_length=150, verbose_name='Identifier')),
            ],
        ),
    ]
