# Generated by Django 2.0.5 on 2018-05-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxtdemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=32)),
                ('orgname_en', models.CharField(max_length=150)),
                ('orgname_fr', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='ati',
            name='orgname_en',
        ),
        migrations.RemoveField(
            model_name='ati',
            name='orgname_fr',
        ),
        migrations.AddField(
            model_name='ati',
            name='dept',
            field=models.ManyToManyField(related_name='ATIs', to='wxtdemo.Department'),
        ),
    ]
