# Generated by Django 2.0.5 on 2018-05-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxtdemo', '0002_auto_20180530_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='acronym',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
